# Generated by Django 5.2.8 on 2025-11-21 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Data",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("location", models.CharField(max_length=1000)),
                ("coordinates", models.CharField(max_length=100)),
                ("operator", models.CharField(max_length=500)),
                ("date", models.DateField()),
                ("level", models.ImageField(upload_to="")),
                ("txt", models.CharField(max_length=100)),
                ("tracking", models.CharField(max_length=500)),
                ("upkeep", models.CharField(max_length=500)),
                ("description", models.TextField()),
            ],
        ),
    ]
