# Generated by Django 5.2.8 on 2025-11-22 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="data",
            name="date",
            field=models.CharField(max_length=100),
        ),
    ]
