import axios from 'axios';


// ai summary fetch
export const fetchAiSummary = async (setLoadingAiSummary, setAiSummary) => {
    try {
        setLoadingAiSummary(true);
        const response = await axios.get(`http://127.0.0.1:8000/api/ai`);
        setAiSummary(response.data);
        console.log("AI summary fetched:", response.data);
/*         setTimeout(() => {
            setAiSummary("This is a mock AI-generated summary based on the selected data. In a real application, this summary would be generated by an AI model analyzing the provided markers and observations.");
        }, 3000); */
        
    } catch (error) {
        console.error("Virhe datan hakemisessa:", error);

    } finally {
        setLoadingAiSummary(false);
    }
}

// post request for ai summary based on date and province
export const getAiSummaryByDay = async (setLoadingDateAiSummary, setAiSummary, postData) => {
    try {
        setLoadingDateAiSummary(true);
        console.log("Lähetettävä data:", postData);
        const response = await axios.post(
            "http://127.0.0.1:8000/api/predict/",
            postData, // Lähetettävä JSON-data
            {
            headers: {
                "Content-Type": "application/json",
            },
            }
        );
        console.log("Vastaus palvelimelta:", response.data);
        const formattedText = formatPredictionData(response.data);
        setAiSummary(formattedText);


    } catch (error) {
        console.error("Virhe datan lähettämisessä:", error);
        console.error("Virheen aiheuttaneet arvot:", postData);
    } finally {
        setLoadingDateAiSummary(false)
    }

}


// post request for markers
export const getMarkers = async (setLoadingMarkers, setMarkersData, postData) => {
    try {
        setLoadingMarkers(true);
    
        if (postData.province != null) {
            console.log("Lähetettävä data:", postData);
            const response = await axios.post(
                "http://127.0.0.1:8000/api/province/",
                postData, // Lähetettävä JSON-data
                {
                headers: {
                    "Content-Type": "application/json",
                },
                }
            );
            console.log("Vastaus palvelimelta:", response.data);
            setMarkersData([...response.data]);
        } else {
            console.log("Epäkelvollinen province, ei löydy id refrencestä")
            setMarkersData([]);
        }
        
    } catch (error) {
        console.error("Virhe datan lähettämisessä:", error);
        console.error("Virheen aiheuttaneet arvot:", postData);
    } finally {
        setLoadingMarkers(false)
    }
}

export const getAllObservationsDates = async (setObservationsData) => {
    try {
        const response = await axios.get("http://127.0.0.1:8000/api/data/");
        console.log("Havaintopäivät haettu:", response.data);

        if (!Array.isArray(response.data)) {
            throw new Error("Vastauksen data ei ole taulukko.");
        }
        const dateCountMap = {};

        response.data.forEach(observation => {
            if (!observation.date) {
                console.warn("Havainnolla ei ole päivämäärää:", observation);
                return;
            }

            const date = new Date(observation.date);

            const dateKey = date.toISOString().split('T')[0];

            if (dateCountMap[dateKey]) {
                dateCountMap[dateKey].count++;
            } else {
                dateCountMap[dateKey] = { date: new Date(dateKey), count: 1 };
            }
        });

        const result = Object.values(dateCountMap);
        console.log("Käsitellyt havaintopäivät:", result);

        setObservationsData(result);

    } catch (error) {
        console.error("Virhe havaintojen hakemisessa:", error);
        setObservationsData([]);
    }
};




function formatPredictionData(data) {
    const location = data.Sijainti || "Tuntematon sijainti";
    const date = data["Päivämäärä"] || "Tuntematon päivämäärä";
    const risk = data["Ennustettu Leväriski"] || "Tuntematon riski";
    const probabilities = data["Todennäköisyydet"] || {};
    const typicalValues = data["Tyypilliset Arvot"] || {};

    // Muotoile todennäköisyydet
    const probabilityText = Object.entries(probabilities)
        .map(([key, value]) => `${key}: ${(value * 100).toFixed(2)}%`)
        .join(", ");

    // Muotoile tyypilliset arvot
    const typicalValuesText = Object.entries(typicalValues)
        .map(([key, value]) => `${key}: ${value.toFixed(2)}`)
        .join(", ");

    return `
        Sijainti: ${location}
        Päivämäärä: ${date}
        Ennustettu leväriski: ${risk}

        Todennäköisyydet:
        ${probabilityText}

        Tyypilliset arvot:
        ${typicalValuesText}
    `;
}


